# Generated by Django 4.0.3 on 2022-07-22 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kor_word', models.CharField(max_length=100, verbose_name='한글 단어')),
                ('eng_word', models.CharField(max_length=100, verbose_name='영어 단어')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='제작일')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('doong_position', models.CharField(blank=True, max_length=10, null=True, verbose_name='둥 위치')),
            ],
        ),
    ]
