# Generated by Django 4.0.3 on 2022-07-22 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doongzipedia', '0002_word_definition_word_example_alter_word_eng_word'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='doong_position',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='둥 위치'),
        ),
    ]
