# Generated by Django 4.0.3 on 2022-08-05 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('how_to_doongzi', '0002_alter_post_content_alter_post_creator'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
