# Generated by Django 4.0.3 on 2022-07-10 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Support',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person', models.CharField(blank=True, max_length=100, null=True, verbose_name='응원자')),
                ('message', models.CharField(blank=True, max_length=100, null=True, verbose_name='응원메시지')),
                ('number', models.IntegerField(verbose_name='응원번호')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='작성일')),
            ],
        ),
    ]
