# Generated by Django 4.0.3 on 2022-07-11 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_support'),
    ]

    operations = [
        migrations.RenameField(
            model_name='support',
            old_name='person',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='support',
            name='number',
        ),
    ]
