# Generated by Django 4.0.3 on 2022-10-09 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_rename_person_support_name_remove_support_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='People',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kor_name', models.CharField(max_length=100, verbose_name='한글이름')),
                ('eng_name', models.CharField(max_length=100, verbose_name='영문이름')),
                ('image', models.ImageField(blank=True, upload_to='image/people')),
                ('domain', models.TextField(blank=True, verbose_name='하는 일')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='작성일')),
                ('phone', models.CharField(blank=True, max_length=100, verbose_name='전화번호')),
                ('email', models.CharField(blank=True, max_length=100, verbose_name='이메일')),
                ('ig', models.CharField(blank=True, max_length=100, verbose_name='인스타그램 아이디')),
            ],
        ),
    ]
