# Generated by Django 4.0.3 on 2023-04-16 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_people'),
    ]

    operations = [
        migrations.AlterField(
            model_name='people',
            name='image',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
