# Generated by Django 4.0.3 on 2022-03-16 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_post_content_remove_post_title_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='내용')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='제작일')),
                ('color', models.CharField(blank=True, max_length=10, null=True, verbose_name='색상')),
                ('positionX', models.CharField(blank=True, max_length=10, null=True, verbose_name='X위치')),
                ('positionY', models.CharField(blank=True, max_length=10, null=True, verbose_name='Y위치')),
            ],
        ),
    ]
