# Generated by Django 4.0.3 on 2022-04-02 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='iframe',
            field=models.TextField(blank=True, verbose_name='iframe'),
        ),
    ]
