# Generated by Django 4.0.3 on 2022-07-10 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_post_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='position_X',
            field=models.IntegerField(blank=True, null=True, verbose_name='가로위치는?'),
        ),
        migrations.AddField(
            model_name='post',
            name='position_row',
            field=models.IntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], null=True, verbose_name='몇번째줄?'),
        ),
    ]
